name: Auto-refresh Render Calendar

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours at minute 0
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        id: trigger
        run: |
          echo "Refreshing calendar..."
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.render.com/deploy/srv-d3uugpjipnbc73985lg0?key=9R9dJBwVqhQ")
          echo "HTTP response code: $RESPONSE"

          if [ "$RESPONSE" -ge 200 ] && [ "$RESPONSE" -lt 300 ]; then
            echo "Calendar refresh successful ✅"
            echo "::set-output name=status::success"
          else
            echo "Calendar refresh failed ❌"
            echo "::set-output name=status::failure"
            exit 1
          fi

      - name: Notify
        run: |
          if [ "${{ steps.trigger.outputs.status }}" == "success" ]; then
            echo "✅ Calendar was refreshed successfully."
          else
            echo "❌ Calendar refresh failed. Check the logs."
          fi
